자바스크립트의 스레드 (코드를 처리하는 일꾼)
자바스크립트는 싱글 스레드

a ... (3초)
b ... (2초)
c ... (5초)
d ... (30초)
e ... (8초)
main ... (5초) --- 53초

싱글 쓰레드인 자바스크립트의 특징은
현재 실행중인 태스크(기능, 구간, 섹션)가 종료되어야만 다음 태스크를 실행합니다.
이러한 특징 때문이 처리 시간이 지연되는 함수의 경우 굉장히 비효율적

따라서 자바스크립트는 이벤트 루프를 활용하여 기존의 태스크가 종료되지 않아도
다음 태스크를 곧바로 실행하는 방식인 비동기 처리방식을 도입 하였습니다.

동기 vs 비동기

동기는 코드를 순차적인 흐름으로 진행

---

- 대표적인 비동기 함수
  setTimeOut, setInterval, Promise

---

비동기 처리

비동기 처리 시간이 각각 다르기 때문에 결과를 예상할 수 없음
따라서 결과에 따라 다음 함수(비동기 이후 실행된 동기적이 함수)를 실행시키기 위하여 비동기를 동기적으로 처리

(1) call back

function 비동기 (callback) { ---> 비동기 함수

setTimeOut(()=> {
console.log("하나")
callback(
setTimeOut(()=>{
console.log("둘")
},1000)
) ------- > 비동기
}, 1000)
} --------------------------------------------------> 콜백 지옥

function callback () { ---> 비동기 이후에 실행되어야 함
setTimeOut(()=>{
console.log("콜백"ㄴ)
}, 1000)
}

- --------------------------------------------------->

(2) promise
ES6에 도입, new 연산자와 함꼐 호출하고 인자로 콜백을 받습니다.
Promise는 호출 시에 바로 실행은 되지만 그 안에 resolve와 recject가 둘중 하나가 호출되기 전에는
then과 catch로 넘어가지 않습니다.

then --> promise 성공했을 때
catch --> promise 실패했을 때

비동기는 항상 성공 할까요

ex)

let num3
const result = new Promise((resolve, reject) => {
비동기 함수 ...
num=2
resolve(num)

resolve(성공 인자)
reject(실패 인자)
}).then((인자) => {
console.log(인자) // 성공 인자
d(인자)
})
.catch((인자) => {
console.log(인자) // 실패 인자
})

d(num)

(3) async await
Promise로 비동기 처리를 한다고 하더라도, 콜백 지옥이 연상되는 것은 마찬가지
비동기를 아예 동기적인 흐름 처리로 만들어버리자
async를 통해 함수를 promise 변환
await을 통해 해당 함수가 실행될 때까지 (promise가 resolve, rject) 대기

async function a(){
}

const a = async () => {
try {

        const result = await new Promise(...)
        console.log(result) --> return promise resolve

    } catech(err) {

        console.log(err) --> return promise reject
        // 예외 상황 처리문
    }

}

promise

let a = 4;

const pr = new Promise((resolve, reject)=> {
setTimeout(()=>{
a += 1;
if(a == 6){
resolve(a)
} else {
reject('error')
}
},1000)
})

pr.then((res) => {
console.log(res); // 6
}).catch((err) => {
console.log(err)
})

console.log("성용")
console.log("123")

promiseAll

const pr1 = new Promise((resolve) => {
setTimeout(()=>{
resolve("안녕하세요")
},1000)
})

const pr2 = new Promise((resolve, reject) => {
setTimeout(()=>{
reject("반갑습니다")
},3000)
})

const pr3 = new Promise((resolve) => {
setTimeout(()=>{
resolve("김성용입니다")
},2000)
})

//all은 배열내의 모든 promise를 실행, 각 인덱스에 맞는 결과값을 반환
//race는 배열 내의 모든 promise 중 가장 빠린 오는 값을 반환
Promise.all([pr1, pr2, pr3]).then((result) => console.log(result)).catch((err)=>{console.log(err)})

// all의 가장큰 단점은 하나라도 실패하면 catch문으로 throw
// status를 통해 fulfilled와 rejected를 나누고 성공과 실패의 분기를 나누어 사용이 가능
// allSettled
Promise.allSettled([pr1, pr2, pr3]).then((result)=>console.log(result))

/\*
예외처리문

try{
...성공과 실패 가능성이 있는 실행문
.. 성공 시 실행할 문장

    throw new Error(err)

}catech(err){
.. 실패시 실행될 문장
}

try문에서 error가 나오면 상위 예외 처리문인 catch문에서
예외를 캐치하여 예외를 처리해준다

\*/

async

const callback = (number) => {
return new Promise((resolve, reject) => {
setTimeout(()=>{
number += 1;
if(number<5) return resolve(number);
reject('err')
}, 3000)
})
}

/_
callback(5)
.then((res) => console.log(res)) // 5
.catch((err) => console.log(err)) // err
_/

// then catch(x) ---> 동기적인 흐름으로 코드를 읽을 수 있다
const asyncAddNumber = async (number) => {
try{
const res = await callback(number)
console.log(res) // 5
}catch(err){
console.log(err) // err
}

}
asyncAddNumber(5)
